//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trimatrixlab.DBContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class trimatrixlab_CVEntities : DbContext
    {
        public trimatrixlab_CVEntities()
            : base("name=trimatrixlab_CVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbContact> tbContacts { get; set; }
        public virtual DbSet<tbGrPortfolio> tbGrPortfolios { get; set; }
        public virtual DbSet<tbGrSkill> tbGrSkills { get; set; }
        public virtual DbSet<tbSkill> tbSkills { get; set; }
        public virtual DbSet<tbSliderIcon> tbSliderIcons { get; set; }
        public virtual DbSet<tbTestimonial> tbTestimonials { get; set; }
        public virtual DbSet<tbAbout> tbAbouts { get; set; }
        public virtual DbSet<tbSocial> tbSocials { get; set; }
        public virtual DbSet<tbInterest> tbInterests { get; set; }
        public virtual DbSet<tbEducation> tbEducations { get; set; }
        public virtual DbSet<tbExperience> tbExperiences { get; set; }
        public virtual DbSet<tbStory> tbStories { get; set; }
        public virtual DbSet<tbPortfolio> tbPortfolios { get; set; }
    }
}
