//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trimatrixlab.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAbout
    {
        public int IDAbout { get; set; }
        public string Name { get; set; }
        public string Contents { get; set; }
        public string Email { get; set; }
        public string Web { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Descriptions { get; set; }
        public string ZipCode { get; set; }
        public string Image { get; set; }
        public string Link { get; set; }
        public string MoTaInterest { get; set; }
        public string Poster { get; set; }
    }
}
