//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trimatrixlab.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbContact
    {
        public int IDContact { get; set; }
        public string Ten { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string NoiDung { get; set; }
        public Nullable<bool> Hide { get; set; }
    }
}
