//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trimatrixlab.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbInterest
    {
        public int IDInterest { get; set; }
        public string Icon { get; set; }
        public string TenIcon { get; set; }
        public string Background { get; set; }
        public Nullable<bool> Hide { get; set; }
    }
}
