//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trimatrixlab.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPortfolio
    {
        public int IDPortfolio { get; set; }
        public Nullable<int> IDGrPortfolio { get; set; }
        public string TieuDe { get; set; }
        public string Portfolio { get; set; }
        public string Image { get; set; }
        public string Link { get; set; }
        public Nullable<bool> Hide { get; set; }
    }
}
