//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trimatrixlab.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSocial
    {
        public int IDSocial { get; set; }
        public string Image { get; set; }
        public string LinkSocial { get; set; }
        public string Button { get; set; }
        public Nullable<bool> Hide { get; set; }
    }
}
